### ISSUE TITLE
Where is source code availabale?

### ISSUE THREAD

**Issue by athulantonynp** [P1nGu1n/PlayStoreChangelog#14]
Hi where is play store source code is available? I wanted to hook some methods in playstore apk. Please help.

**Comment by KevinX8** [comment]
Uh you do know that all Google apps are closed source right? That's why opengapps.org exists

**Comment by P1nGu1n** [comment]
@KevinX8 is right, the Play Store is closed source. I use [jadx](https://github.com/skylot/jadx) to decompile APKs.
